### ISSUE TITLE
non-zero error code returned when wgrib2 is called with no arguments

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/wgrib2#100]
When I call wgrib2 with no arguments, I get some sensible output, but then it errors with an exit code of 8.

Instead, the return code should be 0.

**Comment by webisu** [comment]
This is by design.

Suppose
    $ wgrib2 $file
        where $file refers to non-existing file.
        wgrib2 returns a non-zero code

    $  wgrib2 $file
         where $file is undefined.
         This is a programming error, so wgrib2  returns a non-zero error
code

    $ wgrib2
           This is what wgrib2 sees with the above error.

     $ wgrib2 non-gribfile
            returns 0
            legal grib file

     $ wgrib2 /dev/null
            returns 0
            legal but empty grib file

One could argue that -version, -config, -h, and -help should return
a zero error code.

**Comment by edwardhartnett** [comment]
OK, excellent explanation!

Can you look at the open PRs and approve them? Then I will merge them and show you how to encode what you just told me into an automated test...

**Comment by edwardhartnett** [comment]
This doesn't match what you say above:
