### ISSUE TITLE
support spack build and testing

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/wgrib2#112]
We need to add the wgrib2 package file to this repo, and set up testing with it, just as we have done for the NCEPLIBS. This will allow us to manage the spack package file with releases.

**Comment by edwardhartnett** [comment]
@AlexanderRichert-NOAA we are about to do a release, this will be needed after that.

**Comment by edwardhartnett** [comment]
@AlexanderRichert-NOAA can we get this in the next week or so? We are getting ready for the next release...

**Comment by AlexanderRichert-NOAA** [comment]
To clarify, is the idea to use the cmake-based build? Currently the spack recipe is written for the make-based build.

**Comment by AlexanderRichert-NOAA** [comment]
Also, if that is the case, what version should be the earliest version in the recipe to use cmake?

**Comment by edwardhartnett** [comment]
Yes on the cmake build. Earliest version is 3.2.0, the current release.
