### ISSUE TITLE
Replace iplib and ip2lib_d  by NCEPLIBS-ip

### ISSUE THREAD

**Issue by webisu** [NOAA-EMC/wgrib2#126]
wgrib2 v3.1.3 can be compiled with the old iplib.v3.0.0 or ip2lib_d.  The next version of wgrib2 should be built with NCEPlib-ip because the code is maintained and the need for two versions of the wgrib2 executable can be eliminated.

**Comment by edwardhartnett** [comment]
I believe this has been done but is there any test which confirms that it worked?
