### ISSUE TITLE
Update CPC wgrib2 web page to point to GitHub site

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/wgrib2#146]
There is a web page here:
https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/

This should be modified to direct users to the GitHub site for new releases (and, eventually, documentation).

**Comment by webisu** [comment]
The github wgrib2 is not ready yet. Will do after the github version has
ip, aec, openjpeg, jasper support and we get feedback from average people
on their experience on installing wgrib2 from github.  The latter will be
needed for writing the install directions.

**Comment by edwardhartnett** [comment]
We can wait until the next release, which will have all those features, but no later.

The NCEPLIBS group will not take this software on in competition with CPC. CPC does not want to host the software, so we need their web page to point to the official release, not maintain a divergent release. There must be one and only one home for the software. We do not have the resources for a divided effort.

We do not need user feedback, since no amount of user feedback is going to cause us to go back to makefiles. The install instructions are simple and we do not need to wait for user feedback for those.

@webisu it's certainly worthwhile to be concerned about existing users. But we cannot hold back NOAA progress for them. NOAA is the owner of this software and we need it to work well for NOAA.

Don't worry, outside users can adjust to cmake, because that's what everyone is using now. Anyone who can't figure out  how to use cmake instead of makefiles is already hopeless out of touch - no other software can be built with makefiles any longer. 

It's much more likely that any existing users will be excited and happy to have a cmake release. No one uses makefiles any more, and we are all very happy about that.

**Comment by webisu** [comment]
It is not a competition between CPC or EMC.  I don't want users to waste
their time
installing something that will not meet their needs.  You under-estimate
the need
for proper installation documentation.  I spent many hours trying to
install the ip
library, and I had to ask you for help.  How long will the average user
spend
before giving up?

**Comment by edwardhartnett** [comment]
We will discuss at the meeting today.

In any case, the whole documentation issue is more complex than I first supposed, so let's bump this to the next release and continue to work and discuss...

**Comment by edwardhartnett** [comment]
OK, I've just read the changes to the CPC wgrib2 page and we'll take a look at all the mentioned issues. But this issue has been completed and I will close it.
