### ISSUE TITLE
remove lib subdirectory

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/wgrib2#150]
We should not have a subdirectory named lib, as that is an install subdirectory name, which may lead to confusion. 

ALso it only contains a makefile, which we are no longer supporting and should be removed. So seems like the whole lib subdirectory can be removed.

**Comment by webisu** [comment]
The libs/makefile combines the various libraries to a single library.  With
the makefile system,
the lib/makefile will combine all the *.a to a single *.a.  This makes
programs that build with
libwgrib2 easier to setup.   The python interface requires libwgrib2.so.
This library will probably
have to include the libraries that wgrib2 calls such as aec, png-1.2,
openjpeg.  Maybe you
can get around it by LD_LIBRARY_PATH but I would never suggest that
solution.






The libs/makefile combines the various libraries to a single *.so file.  It
is not clear  how to run with multiple libraries without LDPATH.

**Comment by webisu** [comment]
I am not saying to keep libs/makefile or libs but something will have to be
done to combine libraries that lib/makefile does.

**Comment by edwardhartnett** [comment]
OK, we'll take a look at that...
