### ISSUE TITLE
Parallel build fails

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [NOAA-EMC/wgrib2#158]
When building under Spack with parallel make, I sometimes get the following error:
```Fatal Error: Can't rename module file 'wgrib2lowapi.mod0' to 'wgrib2lowapi.mod': No such file or directory```
which would seem to indicate a missing target dependency.

**Comment by AlysonStahl-NOAA** [comment]
Which options lead to this error exactly? I can't seem to recreate it. I'm wondering if this has been fixed already by some other updates.

**Comment by AlexanderRichert-NOAA** [comment]
This happens with MAKE_FTN_API enabled:
```console
git clone https://github.com/NOAA-EMC/wgrib2
cmake -B wgrib2/build -S wgrib2/ -DMAKE_FTN_API=ON
cmake --build wgrib2/build/ -j2
```
If I try to build it without the `-j2` I get a different error, but that seems to be unrelated...

**Comment by AlysonStahl-NOAA** [comment]
I'm unable to duplicate the error you got, however with and without the -j2 I get the following error. Is this the error you're getting without the -j2 ?

>/usr/lib/gcc/i686-pc-cygwin/11/../../../../i686-pc-cygwin/bin/ld: CMakeFiles/obj_lib.dir/ftn_api/fort_wgrib2.c.o: in function `wgrib2c':
/home/mobaxterm/MyDocuments/GitHub/wgrib2/wgrib2/ftn_api/fort_wgrib2.c:43: undefined reference to `wgrib2'
collect2: error: ld returned 1 exit status
make[2]: *** [wgrib2/CMakeFiles/wgrib2_exe.dir/build.make:684: wgrib2/wgrib2.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:983: wgrib2/CMakeFiles/wgrib2_exe.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by AlexanderRichert-NOAA** [comment]
Yes, that's the other error I'm seeing.

That's odd about it not reproducing. Is there an R&D system like Hera or Orion that you have access to where I can set up a test?

**Comment by AlysonStahl-NOAA** [comment]
I have access to Hera now, but I haven't used it too much yet. I did just try this out on there and reproduced the error.
