### ISSUE TITLE
Change CPC website to point to GitHub site

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/wgrib2#166]
Starting with the 3.4.0 release, the CPC website will direct users to the github site.

There will be only one distribution site for wgrib2, and it is the wgrib2 GitHub site. All distributions and documentation will be found on the GitHub site.

Change README.md to contain github site and not to point to CPC site.

**Comment by edwardhartnett** [comment]
THis will take effect after the 3.4.0 release, so I will move it to 3.5.0.

**Comment by webisu** [comment]
I changed the CPC web site to point to github.  However, I
pointed out the status of v3.3.0 vs v3.1.3.  BTW v3.3.0 doesn't
work with ip because it links in ip_4 rather than ip_d.  I just
tested Alex's changes for WMO rotated lat-lon, and it handled
my sample COSMO file correctly.

**Comment by edwardhartnett** [comment]
You say:

> v3.3.0 doesn't
> work with ip because it links in ip_4 rather than ip_d. 

Can we have a unit test that demonstrates this? I will start an issue for this.

**Comment by edwardhartnett** [comment]
This is a duplicate of #146. I will close this issue...
