### ISSUE TITLE
add authors to README

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/wgrib2#168]
Wesley Ebisuzaki, Reinoud Bokhorst, John Howard, Jaakko Hyvätti, Dusan Jovic, \
Daniel Lee, Kristian Nilssen, Karl Pfeiffer, Pablo Romero, Manfred Schwarb, Gregor Schee, Arlindo da Silva, \
Niklas Sondell, Sam Trahan, George Trojan, Sergey Varlamov

**Comment by webisu** [comment]
Need to add people who are doing the CMake build and testing.

**Comment by edwardhartnett** [comment]
Good idea, I have done so.
