### ISSUE TITLE
document what's up with the get_code_*.sh scripts. What are the used for?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/wgrib2#172]
@webisu I see we have a bunch of scripts which apparently get the WMO CVS file for a table.

Are these CSV files then used by wgrib2, or is this just for reference? That is, do these shell scripts get called in normal wgrib2 operation? Or are they run by you when programming to get the WMO table, which you then use while coding? Or something else?

Do these scripts get installed for users?

If so, we have to offer an option where they do not get installed, because NCO does not want any scripts like this installed on WCOSS2.

**Comment by webisu** [comment]
These codes are run to update various tables that are used by wgrib2.
These scripts are run whenever someone
sees a change in the tables and wants to update wgrib2.  Updating the
tables has to be done with caution because
it can change the text output.  One should also check the code that uses
the table to see if changes affect its operation.

**Comment by edwardhartnett** [comment]
Are the tables also already included in the repo?

In other words, these scripts do not have to be run as part of wgrib2 install, correct? The wgrib2 install will come with all the tables it already needs, updated the last time you (or another wgrib2 developer) ran those scripts.

**Comment by webisu** [comment]
The *.sh scripts are run by the developer to update *.c, *.h and *.dat (C
code fragments).
Some *.sh scripts rarely get run while others are run whenever an option
has a "major"
change.  Downloading the latest NCEP grib table is done at least once
before a new
release.  Getting rid of the *.sh files means that there will need a second
version for
developers.

**Comment by edwardhartnett** [comment]
We will not get rid of them, we just can't install them or run them on high-FISMA platforms.

But if they are run by the developers that is not a problem.

**Comment by edwardhartnett** [comment]
I will update the documentation in the scripts to include this info.
