### ISSUE TITLE
require NCEPLIBS-ip-5.1.0 in the cmake build (after it is released)

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/wgrib2#189]
Soon @AlexanderRichert-NOAA will release NCEPLIBS-ip-5.1.0 which will have the rotated lat/lon interpolation.

Once that happens, does wgrib2 always require NCEPLIBS-ip-5.1.0 or better? Or can we still work with older versions of ip/sp? 

In cmake we have:

```
# If user wants to use NCEPLIBS-ip, find it and the sp library.
message(STATUS "Checking if the user want to use NCEPLIBS-ip...")
if(USE_IPOLATES)
  find_package(ip CONFIG REQUIRED)
  list(APPEND definitions_list -DIPOLATES_LIB="ipolates_lib_4")
  list(APPEND definitions_list -DUSE_IPOLATES)
endif()
```

We need to decide about the version, whether sp is ever required, and check that in the cmake.

I think this assumes ip 5.0.0.

In fact, for

**Comment by webisu** [comment]
You really need ip v5.1.0+ once v5.1.0 is released.  Some centers are making
the rotated lat-lon grid the primary grid for the regional models.
The advantage
is that you can avoid a double interpolation error.

**Comment by edwardhartnett** [comment]
OK, so we need to ensure that the CMake build enforces that by requiring ip-5.1.0 (when it comes out).

We will still be able to build without ip, correct?

**Comment by webisu** [comment]
Can build without ip as long as it  is turned off in CMakeLists.txt.

**Comment by AlexanderRichert-NOAA** [comment]
It is released: https://github.com/NOAA-EMC/NCEPLIBS-ip/releases/tag/v5.1.0
