### ISSUE TITLE
NCEPLIBS-ip   NAM rotated lat-lon

### ISSUE THREAD

**Issue by webisu** [NOAA-EMC/wgrib2#216]
I updated my NCEPLIBS/ip to v5.1.0.  Rebuilt wgrib2 and
tried it on my WMO rotated lat-lon (COSMO), and it worked.
However my NCEP rotated lat-lon (NAM) file failed to give
the proper domain.
![junk](https://github.com/user-attachments/assets/ecc61900-e47e-4f0b-bd1c-1aea7505d5c8)

**Comment by webisu** [comment]
Still not fixed.

**Comment by edwardhartnett** [comment]
@AlexanderRichert-NOAA please note...

**Comment by AlexanderRichert-NOAA** [comment]
This looks a lot like what we were seeing before. @webisu please provide a case to reproduce, including a specific commit of wgrib2 code to test with.

**Comment by AlexanderRichert-NOAA** [comment]
Is that with `use_ncep_post_arakawa()`?

**Comment by webisu** [comment]
fixed
