### ISSUE TITLE
remove references to G95 and other specific Fortrans

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/wgrib2#225]
In wgrib2/New_grid.c we have:

```
#ifdef G95
        // initialize g95 runtime library
        if (g95_runstop == 0) { g95_runtime_start(0,NULL); g95_runstop = 1; }
#endif

```

What's this all about? I've never seen any other program that required this.

In our code there should be no reference to specific Fortran compilers. Fully standard Fortran runs on all compilers, and that's all we should be using.

**Comment by webisu** [comment]
A long time ago, g95 was better than gfortran.  In order to call a g95
compiled
routine from C, you had to initialize the g95 run time library.  I don't
know
whether this is still true.  I haven't used g95 in years.   We should get
rid of g95 support since it hasn't been tested.

**Comment by webisu** [comment]
Reference to G95 was eliminated when New_grid.c was rewritten for the new iplib.
The change also made the calling to fortran standard.
