### ISSUE TITLE
netCDF changes

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/wgrib2#227]
There is only one netCDF, not 3 or 4, so remove all options relating to 3/4 in the build.

When creating a netCDF file, the nc_create() mode flag determines the binary format:
NC_NETCDF4 - create a HDF5 file
NC_NETCDF4|NC_CLASSIC_MODEL - create a HDF5 file but adhere to classic model

In cmake we need to determine if netCDF supports HDF5.

If you want require netCDF with HDF5, we can check that in configure.

**Comment by webisu** [comment]
Changes have been done. Issue can be closed.
