### ISSUE TITLE
Some of the web docs files have the same name

### ISSUE THREAD

**Issue by AlysonStahl-NOAA** [NOAA-EMC/wgrib2#244]
Under the web_docs subdirectory, some of the html files have the same names with a different case on the first letter.

For example, we have V.html and v.html or Match_inv.html and match_inv.html.

This is causing issues for me locally where only one file can exist at a time and the files try to overwrite one another.

**Comment by webisu** [comment]
If you developing with windows, you can make your Windows directories case
sensitive.

https://learn.microsoft.com/en-us/windows/wsl/case-sensitivity

This may fix your problem.  I agree that source files should not have file
names
that duplicate each other in a case insensitive file system.  Many of the
web_doc
filenames are "OPTION.html" and there are upper and lower case versions of
the options.
(Lower case versions use a date code that ends in the hour.  Upper case
versions
use a date code that ends in seconds.)  It would be shame to alter this
simple
naming convention.

**Comment by edwardhartnett** [comment]
That does not fix the problem.

The naming convention may be simple and elegant, but Bill Gates broke it when he decided that Windows does not have case-sensitive file names. You may add your curses to the vast cloud of curses that have already been heaped up poor Bill for this and other questionable design decisions he made many decades ago, which we are still stuck with now.

So we need to rename files that have the same name, and we need all links to them to be updated to the new name.

**Comment by webisu** [comment]
How about the convention
   s.html -> s.html
   S.html -> S.htm

**Comment by edwardhartnett** [comment]
How about:
s.html
S_1.html

**Comment by webisu** [comment]
There is an issue that I hadn't thought about.  There is a script that
generates two index pages.

    https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/short_cmd_list.html
    https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/long_cmd_list.html


It reads the output from
     $ wgrib2
     $ wgrib2 -help all

The script checks to see whether XXX.html exists in order to create
the index web page.  It would be easier for any program that generates
the index pages if you have a convention for options that start with a lower
case and another option for options that start with an upper case.  (This
assumes that there are no more than two files with the same windows name.)

[a-z]*.html -> [a-z]*.html
[A-Z]*.html -> [A-Z]*_.html

**Comment by edwardhartnett** [comment]
OK, is this documentation generation script in the repo?

**Comment by webisu** [comment]
No.  I don't think it is a good idea to put active scripts into a directory
that is
visible to the public like the *.html.  It's a very simple script that
changes
the short/long listings of the options into a web page.  For each
(name).html
it checks to see whether (name) is an option.  If it is an option, it
replaces
the option name by a hyperlink.
