### ISSUE TITLE
Intel Classic & oneAPI support/CI testing

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [NOAA-EMC/wgrib2#250]
What's the status of wgrib2 support for Intel compilers, especially for oneAPI? I don't see CI workflows for wgrib2 for testing with Classic or oneAPI-- I suggest we add some.

**Comment by webisu** [comment]
Wgrib2 v3.1.3 supported both Classic and OneAPI intel compilers.  Wgrib2
also supports
clang/flang (from the AOCC package).  Something may be wrong with the
Nvidia/Portland support.  They
used to work but the last time I tried it, wgrib2 was acting strangely.
The only major change in
wgrib2 is moving to the standard C to fortran interface for calling the
iplib. Should be tested.
Found weird bugs in the intel libraries and unusual behaviors in the intel
compiler.  (We don't
support f95 but if you use f95 syntax we will just compile it incorrectly.)
