### ISSUE TITLE
png support for large files.

### ISSUE THREAD

**Issue by webisu** [NOAA-EMC/wgrib2#251]
wgrib2 fails for a  lat-lon grid:(7000 x 3500) .  The permissible image width needs to be increased.

**Comment by webisu** [comment]
The pre-github version of wgrib2 supported large PNG grids by compiling pnglib with a larger buffer.  This patch enables similar support using a pnglib compiled with the default buffer size.

**Comment by edwardhartnett** [comment]
Don't forget to add a test...

**Comment by webisu** [comment]
Test was added.

**Comment by AlysonStahl-NOAA** [comment]
This issue should be closed by #252 , but it linked the wrong issue. Closing now.
