### ISSUE TITLE
wgrib_exe target is built without definitions_list, breaking USE_REGEX silently

### ISSUE THREAD

**Issue by himikof** [NOAA-EMC/wgrib2#29]
Thank you for your work in getting wgrib2 to be built with CMake, as it makes building it much easier!

Unfortunately, I have noticed the following annoying problem: any USE_REGEX-dependent features in the `wgrib2` binary do not work at all (silently).

The reason is that you use the "manually-included OBJECT library" CMake idiom, without propagating the requirements manually:
```cmake
add_library(obj_lib OBJECT ${lib_src})
target_compile_definitions(obj_lib PUBLIC ${definitions_list}) 

add_executable(wgrib2_exe $<TARGET_OBJECTS:obj_lib> ${callable_src})
```

This does not propagate any of the `obj_lib` PUBLIC/INTERFACE properties to the `wgrib2_exe` target, so it does not get the `USE_REGEX` define from `${definitions_list}`.
One way to solve this would be to duplicate the `target_compile_definitions` call for the `wgrib2_exe` and `wgrib2_lib` targets. Another would be to use a genexp like
```cmake
target_compile_definitions(wgrib2_exe PRIVATE
    $<TARGET_PROPERTY:obj_lib,INTERFACE_INCLUDE_DIRECTORIES>)
```
If you can depend on modern CMake, since 3.12 you can just link the OBJECT library, propagating everything automatically:
```cmake
# Requires CMake >= 3.12
add_executable(wgrib2_exe ${callable_src})
target_link_libraries(wgrib2_exe PRIVATE obj_lib)
```
See https://cmake.org/cmake/help/v3.12/command/target_link_libraries.html#linking-object-libraries.

**Comment by kgerheiser** [comment]
Thanks, I'll check this out
