### ISSUE TITLE
Check for OpenMP_C_FOUND instead of OpenMP_FOUND

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/wgrib2#45]
If OpenMP Fortran is found through one of wgrib2's dependencies (ip2 or sp) then `OpenMP_FOUND` is set as true.

wgrib2 checks `if(OPENMP_FOUND)` and will try to link to OpenMP::OpenMP_C.

On macOS Clang doesn't support OpenMP, but gfortran does. So, if one of the Fortran libraries is built with OpenMP then OpenMP_FOUND is true (because OpenMP Fortran is found), then wgrib2 will attempt to link to `OpenMP::OpenMP_C`, resulting in an error because the C version of OpenMP was never searched for.

wgrib2 should instead check `OpenMP_C_FOUND`

**Comment by edwardhartnett** [comment]
Does this need to go into hpc-stack-1.1.0?
