### ISSUE TITLE
Problem building the UPP

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/wgrib2#47]
From @WenMeng-NOAA in https://github.com/NOAA-EMC/hpc-stack/issues/53#issuecomment-732172302

> I got runtime error from the UPP test with wgrib2/2.0.8 as:
> 0.001 + wgrib2 tmpfile1_006_4 -set_grib_type same -new_grid_winds earth -new_grid_interpolation bilinear -if ':(CSNOW|CRAIN|CFRZR|CICEP|ICSEV):' -new_grid_interpolation neighbor -fi -set_bitmap 1 -set_grib_max_bits 16 -if ':(APCP|ACPCP|PRATE|CPRAT):' -set_grib_max_bits 25 -fi -if ':(APCP|ACPCP|PRATE|CPRAT|DZDT):' -new_grid_interpolation budget -fi -new_grid latlon 0:1440:0.25 90:721:-0.25 pgb2file_006_4_0p25 -new_grid latlon 0:360:1.0 90:181:-1.0 pgb2file_006_4_1p0 -new_grid latlon 0:720:0.5 90:361:-0.5 pgb2file_006_4_0p5 IPOLATES package is not installed IPOLATES package is not installed IPOLATES package is not installed IPOLATES package is not installed
> 
> I had reported it in another issue somehow can't find the issue number.

**Comment by kgerheiser** [comment]
I believe this is fixed in hpc-stack with https://github.com/NOAA-EMC/hpc-stack/pull/76 since USE_IPOLATES was enanbled

**Comment by WenMeng-NOAA** [comment]
Is the fix implemented on hpc-stack on Hera or other platforms?

**Comment by kgerheiser** [comment]
Not yet. 

We are doing a release today and will start installing it.

**Comment by WenMeng-NOAA** [comment]
Sounds good to me. Please give me a head-up when the new version is ready for testing. Thanks!
