### ISSUE TITLE
Extended names and csv output produces no output

### ISSUE THREAD

**Issue by jordan-evens** [NOAA-EMC/wgrib2#50]
Using `-set_ext_name` with any value other than 0 produces no output when also using `-csv -`

Tried with v3.0.0 and v3.0.2.

Extended names used to be the default in v1.9.4 - in the process of upgrading I noticed that changed and that the `-set_ext_name` flag is supposed to restore the previous functionality. When `-csv -` is not specified it produces a result, but combining the flags means nothing gets outputted.

**Comment by kgerheiser** [comment]
I have forwarded your report to the main developer of wgrib2. This is a CMake branch of wgrib2 used for certain NOAA applications.

**Comment by kgerheiser** [comment]
@jordan-evens could you contact wesley.ebisuzaki@noaa.gov with your bug report.

**Comment by jordan-evens** [comment]
Okay done. Thanks for your help.
