### ISSUE TITLE
wgrib2 shows **** ERROR: local table = 0 is not allowed, set to 1 *** on file provided by French national meteorological service

### ISSUE THREAD

**Issue by matthieumarrast** [NOAA-EMC/wgrib2#52]
Wgrib2 produced by Météo-France (French national meteorological service) - downloaded at address https://mf-models-on-aws.org/#arome-france-hd/v1/2022-02-07/06/SP2/ - shows a **ERROR: local table = 0 is not allowed, set to 1** error message :

```
$ wgrib2 W_fr-meteofrance,MODEL,AROME+001+SP2+01H_C_LFPW_202202040600--.grib2
1:0:d=2022020406:RPRATE:surface:0-1 hour acc fcst:
2:2085086:d=2022020406:SPRATE:surface:0-1 hour acc fcst:
3:2868363:d=2022020406:GPRATE:surface:0-1 hour acc fcst:
4:3774980:d=2022020406:PRES:surface:1 hour fcst:
5:8447856:d=2022020406:LCDC:surface:1 hour fcst:
6:10566565:d=2022020406:HCDC:surface:1 hour fcst:
7:12348291:d=2022020406:MCDC:surface:1 hour fcst:
8:13786664:d=2022020406:CAPE:surface - 3000 m above ground:1 hour fcst:
**** ERROR: local table = 0 is not allowed, set to 1 ***
9:18101192:d=2022020406:var discipline=0 center=85 local_table=0 parmcat=16 parm=193:surface:1 hour fcst:
```

**Comment by edwardhartnett** [comment]
We do not support wgrib2 and recommend that other utilities be used instead. For support of wgrib2 see https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/.

**Comment by webisu** [comment]
According to WMO standards, when the local table (Code Table 1.1) is zero then
"only table entries and templates from the current master table are valid".  However,
field #9 is using a locally defined value (parm=193).  This is a common grib error,
and wgrib2 assumes that Code Table 1.1 is 1.  This message is intended for the producers
of the grib file to fix their files.
