### ISSUE TITLE
wgrib2-2.0.8 does not build on hercules 

### ISSUE THREAD

**Issue by GeorgeVandenberghe-NOAA** [NOAA-EMC/wgrib2#57]
wgrib2-2.0.8 does not compile on hercules with any available intel compiler.  It fails with

make[1]: Leaving directory '/work/noaa/noaatest/gwv/herc/netp4g/nt/wgrib2-2.0.8/gctpc/source'
cp /work/noaa/noaatest/gwv/herc/netp4g/nt/wgrib2-2.0.8/gctpc/source/libgeo.a /work/noaa/noaatest/gwv/herc/netp4g/nt/wgrib2-2.0.8/lib
cp /work/noaa/noaatest/gwv/herc/netp4g/nt/wgrib2-2.0.8/gctpc/source/proj.h /work/noaa/noaatest/gwv/herc/netp4g/nt/wgrib2-2.0.8/include/
cd "wgrib2" && export LDFLAGS="-L/work/noaa/noaatest/gwv/herc/netp4g/nt/wgrib2-2.0.8/lib -lifcore -lc -limf -lintlc -lgeo -lm" && export CPPFLAGS="-I/work/noaa/noaatest/gwv/herc/netp4g/nt/wgrib2-2.0.8/include -O2 -DIFORT -cxxlib -I/usr/include " && export FFLAGS=""" -c -O2 -nofor_main  -cxxlib" && make lib
make[1]: Entering directory '/work/noaa/noaatest/gwv/herc/netp4g/nt/wgrib2-2.0.8/wgrib2'
makefile:63: warning: ignoring prerequisites on suffix rule definition
icc -c -I/work/noaa/noaatest/gwv/herc/netp4g/nt/wgrib2-2.0.8/include -O2 -DIFORT -cxxlib -I/usr/include    AAIG.c
icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
**_In file included from wgrib2.h(8),
                 from AAIG.c(6):
config.h(2): error: unrecognized token
  \#define USE_REGEX
  ^

In file included from wgrib2.h(8),
                 from AAIG.c(6):
config.h(2): error: expected a declaration
  \#define USE_REGEX
  ^

In file included from wgrib2.h(8),
                 from AAIG.c(6):
config.h(2): error: "#" not expected here
  \#define USE_REGEX
   ^

In file included from wgrib2.h(8),
                 from AAIG.c(6):
config.h(3): error: unrecognized token
  \#define USE_TIGGE
  ^

In file included from wgrib2.h(8),
                 from AAIG.c(6):
config.h(3): error: "#" not expected here
  \#define USE_TIGGE

.. .. .._**

**Comment by GeorgeVandenberghe-NOAA** [comment]
This is considerably less urgent than first thought because , after 3.1.1 module errors on hercules, I thought 2.0.8 was required.  It turns out the hercules default wgrib2 module is defective but the spack-stack one provides appropriate settings to a working built distribution at 3.1.1 which means 3.1.1 works for global-workflow/gfs_utils .   The next test to download and build 3.1.1 survived compilation and a preliminary test but this still needs more rigorous testing from my build.   The overall message of this comment though is that 2.0.8 is old, 3.1.1 works and urgency of the 2.0.8 failure to build is MUCH reduced, perhaps moot.

**Comment by edwardhartnett** [comment]
OK so lets close this issue...
