### ISSUE TITLE
any easy unit tests available?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/wgrib2#74]
We have a working make build.

What commands would be used to run existing test code? We can build these into our CI, and convert these tests to working unit tests...

**Comment by edwardhartnett** [comment]
Try the grib2_verify directory.

**Comment by edwardhartnett** [comment]
@webisu there is no grib2_verify directory...

**Comment by webisu** [comment]
Ed,
  It's on my workstation: /cpc/home/wd51we/grib2_verify
My development code resides on /cpc/home/wd51we/grib2
The dev directory for pywgrib2_s is at
     /cpc/home/wd51we/.local/lib/python3.6/site-packages
Wesley

**Comment by edwardhartnett** [comment]
Can we check this code into the repo under a tests subdirectory?

**Comment by edwardhartnett** [comment]
@webisu will provide me with a test script.

**Comment by edwardhartnett** [comment]
@AlysonStahl-NOAA has made a great deal of progress with this.
