### ISSUE TITLE
Remove proj-4.8.0.tar.gz from the repo

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/wgrib2#82]
We need to remove proj-4.8.0.tar.gz from the build.

I note that the readme says:

```
Proj4 is a open-source geolocation library.  Usually the faster gctpc library
is used for geolocation.  At the current time, Proj4 does not add any
capabilty over gctpc.

```
So it sounds like proj4 should just be dropped. Does that make sense?

**Comment by webisu** [comment]
Ed,
   That comment is old.  Proj4 should be replaced by the current
version of Proj (and tested).
Wesley

**Comment by edwardhartnett** [comment]
OK, proj is an external project, correct?

**Comment by edwardhartnett** [comment]
@AlysonStahl-NOAA have you removed all tarballs from the repo?

**Comment by AlysonStahl-NOAA** [comment]
Yep, that's taken care of.
