### ISSUE TITLE
add build option USE_IPOLATES to use the NCEPLIBS-ip and sp libraries

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/wgrib2#92]
add build option USE_IPOLATES to use the NCEPLIBS-ip and sp libraries

**Comment by edwardhartnett** [comment]
The goal is to use only the NCEPLIBS-ip library, and no internal copies of any of this code. Currently we have subdirectories [ip2lib_d](https://github.com/NOAA-EMC/wgrib2/tree/develop/ip2lib_d), [iplib.v3.0.0](https://github.com/NOAA-EMC/wgrib2/tree/develop/iplib.v3.0.0), and [iplib_hwrf](https://github.com/NOAA-EMC/wgrib2/tree/develop/iplib_hwrf) which look like (possibly modified) copies of the ip code.

**Comment by edwardhartnett** [comment]
This can be bumped to the next release.

**Comment by webisu** [comment]
Working except for NCEP-defined rotating lat-lon grids.

   https://github.com/NOAA-EMC/wgrib2/tree/ip_we_1

I needs to try building with non-develop brand of IP.

**Comment by edwardhartnett** [comment]
Can this be closed now?

**Comment by AlysonStahl-NOAA** [comment]
Yes, I'll go ahead and close it.
