### ISSUE TITLE
convert to modern C/Fortran API

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/wgrib2#96]
In ipolates.h we have:

#ifdef G95
#define IPOLATES ipolates_
#define IPOLATEV ipolatev_
void g95_runtime_start(int ,char **);
void g95_runtime_stop(void);
static int g95_runstop = 0;
#endif

#ifdef GFORTRAN
#define IPOLATES ipolates_
#define IPOLATEV ipolatev_
#endif

#ifdef OPENF95
#define IPOLATES ipolates_
#define IPOLATEV ipolatev_
#endif

#ifdef IFORT
#define IPOLATES ipolates_
#define IPOLATEV ipolatev_
#endif

#ifdef FLANG
#define IPOLATES ipolates_
#define IPOLATEV ipolatev_
#endif

#ifdef NVFORTRAN
#define IPOLATES ipolates_
#define IPOLATEV ipolatev_
#endif

#ifdef XLF
#define IPOLATES ipolates
#define IPOLATEV ipolatev
#endif

#ifdef CRAYCE
#define IPOLATES ipolates_
#define IPOLATEV ipolatev_
#endif

#ifdef SOLARIS
#define IPOLATES ipolates_
#define IPOLATEV ipolatev_
#endif

Instead of this, we need to use the modern C/Fortran API that's now part of the fortran standard.

**Comment by edwardhartnett** [comment]
@webisu are we now using standard Fortran when calling ip?

**Comment by webisu** [comment]
The  nceplib/ip now has C callable routines which wgrib2
now uses.
